/**
 * InsightStore schema — the persistence contract for quality insights produced by Horus agents.
 *
 * Each time a Horus agent runs, the caller stores an InsightRecord in the insight store.
 * The store is queryable by repo, branch, agent, and time range so Iris and other agents
 * can pull historical data for trend analysis.
 */

import type {
  FelixOutput,
  GretaOutput,
  IrisOutput,
  PercyOutput,
  KurtOutput,
} from '../contracts/index.js';

// ---------------------------------------------------------------------------
// Agent slug literals — must match horus agent frontmatter names
// ---------------------------------------------------------------------------

export type HorusAgentSlug =
  | 'horus-felix-failure-triage'
  | 'horus-greta-coverage-analyst'
  | 'horus-iris-insight-reporter'
  | 'horus-percy-pr-reviewer'
  | 'horus-kurt-striker-mutation-analyst';

// ---------------------------------------------------------------------------
// Per-agent payload discriminated union
// ---------------------------------------------------------------------------

export interface FelixInsight {
  agentSlug: 'horus-felix-failure-triage';
  payload: FelixOutput;
}

export interface GretaInsight {
  agentSlug: 'horus-greta-coverage-analyst';
  payload: GretaOutput;
}

export interface IrisInsight {
  agentSlug: 'horus-iris-insight-reporter';
  payload: IrisOutput;
}

export interface PercyInsight {
  agentSlug: 'horus-percy-pr-reviewer';
  payload: PercyOutput;
}

export interface KurtInsight {
  agentSlug: 'horus-kurt-striker-mutation-analyst';
  payload: KurtOutput;
}

export type InsightPayload =
  | FelixInsight
  | GretaInsight
  | IrisInsight
  | PercyInsight
  | KurtInsight;

// ---------------------------------------------------------------------------
// Top-level record stored in the insight store
// ---------------------------------------------------------------------------

export interface InsightRecord {
  /** UUID v4 — generated by the caller before storage. */
  id: string;
  /** ISO-8601 timestamp of when the agent was invoked. */
  timestamp: string;
  /** Repo identifier, e.g. "org/repo-name". */
  repoSlug: string;
  /** Git branch at the time of the run. Omit for repo-level insights. */
  branch?: string;
  /** CI run identifier (e.g. GitHub Actions run ID). */
  runId?: string;
  /** PR number, if this insight was generated for a pull request event. */
  prNumber?: number;
  /** Agent slug + typed payload. */
  insight: InsightPayload;
  /** Token usage from the agent call — useful for cost tracking. */
  usage: {
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens: number;
    cacheCreationTokens: number;
  };
}

// ---------------------------------------------------------------------------
// Query filter — passed to InsightStore.query()
// ---------------------------------------------------------------------------

export interface InsightQuery {
  repoSlug: string;
  agentSlug?: HorusAgentSlug;
  branch?: string;
  /** ISO-8601 lower bound (inclusive). */
  since?: string;
  /** ISO-8601 upper bound (exclusive). */
  until?: string;
  /** Maximum number of records to return. Default: 100. */
  limit?: number;
}

// ---------------------------------------------------------------------------
// Minimal store interface — implement with any backend (Postgres, DynamoDB, SQLite, etc.)
// ---------------------------------------------------------------------------

export interface InsightStore {
  /** Persist a new insight record. Throws on write failure. */
  save(record: InsightRecord): Promise<void>;
  /** Retrieve a single record by ID. Returns undefined if not found. */
  get(id: string): Promise<InsightRecord | undefined>;
  /** Query records matching the filter, ordered by timestamp descending. */
  query(filter: InsightQuery): Promise<InsightRecord[]>;
  /** Delete a record by ID. No-ops if not found. */
  delete(id: string): Promise<void>;
}
